Newsletters Module
blacklanternsecurity/bbot pull request #1072
Opened 2024-02-06 21:02 UTC by stryker2k2

### Description:
- Created a new module called 'newsletters' that will scrap the websites (or recursive websites, thanks to BBOT's sub-domain enumeration) looking for the presence of an 'email type' that also contains a 'placeholder'. The combination of these two HTML items usually signify the presence of an "Enter Your Email Here" type Newsletter Subscription service. This module could be used to find newsletters for a future email bombing attack and/or find user-input fields that could be be susceptible to overflows or injections.

### Ticket/Issue
- https://github.com/blacklanternsecurity/bbot/issues/1056

### To Review:
- [x] Run BBOT Module on a website without a Newsletter (ex: blacklanternsecurity.com)
    - `bbot -m httpx newsletters -t blacklanternsecurity.com`
    - Expect 0 Newsletter Events
- [x] Run BBOT Module on a website WITH a Newsletter (ex: futureparty.com)
    - `bbot -m httpx newsletters -t futureparty.com`
    - Expect 1 or more Newsletter Events
- [x] View output on neo4j to ensure it displays well
- [x] Code Review
- [x] Tests Review

### Notes:
- Must be ran with with 'httpx'
- `bbot -m httpx newsletters -t <insert target here>`

2024-02-07 15:23 UTC, stryker2k2 commented
I will be resolving the merge conflicts (via command line) as well as modifying the test_module_newsletters. I'd like to make two checks, one for WITH newsletters and one for WITHOUT newsletters. I currently have one check that fails if either one doesn't pass.

2024-02-08 18:59 UTC, TheTechromancer requested changes

2024-02-08 18:59 UTC, TheTechromancer commented on bbot/modules/newsletters.py
> +    flags = ["passive", "safe"]
"passive" here should be "active" since it relies on web requests.

2024-02-08 18:59 UTC, TheTechromancer commented on lint-tests.sh
We already have a file for this, `bbot/test/run_tests.sh`.

2024-02-09 17:00 UTC, TheTechromancer approved these changes

2024-02-09 18:44 UTC, merged

2024-02-09 20:37 UTC, stryker2k2 commented
Yippie!