Newsletters Error (BeautifulSoup Helper)
blacklanternsecurity/bbot pull request #1154
Opened 2024-03-06 21:38 UTC by stryker2k2

### Description:
- Newsletters (along with dnsdumpster and viewdns) utilize the newly created BeautifulSoup Helper. But, there are instances where BeautifulSoup Helper would return "False" and the modules were not created to handle that boolean. I have gone through each module and added a Try/Catch to them. To prove that the try/catch would work as intended, I tested it by forcing the helper.beautifulsoup to always return False then I ran a scan.

### Ticket/Issue
- https://github.com/blacklanternsecurity/bbot/issues/1138

### To Review:
- [x] Run BBOT normally with these modules using the following command
    - `bbot -m httpx newsletters dnsdumpter viewdns -t example.com`
    - Expect everything to work fine (with results from modules, if target permits)
- [x] Run BBOT after setting the BeautifulSoup Helper to return False
    - bbot/core/helpers/web.py:623
        - return ~~soup~~ False
    - `bbot -m httpx newsletters dnsdumpter viewdns -t example.com`
    - Expect everything to work fine (with NO RESULTS from selected modules)
    - Expect no crashes (as seen in #1138)

### Notes:
- This fixes the issue and will prevent BBOT from crashing... but I still wonder why BeautifulSoup didn't work as intended in https://github.com/blacklanternsecurity/bbot/issues/1138

2024-03-07 12:38 UTC, TheTechromancer requested changes

2024-03-07 12:38 UTC, TheTechromancer commented on bbot/modules/newsletters.py
> +                pass
There's no reason to wrap in a blanket try/except here since you're already checking for falsiness.

2024-03-07 12:38 UTC, TheTechromancer commented on bbot/modules/dnsdumpster.py
> +            pass
Again, the try/except will not catch the error because it's being caught already in the helper. Something like `if html is False: return` would suffice.

2024-03-07 19:46 UTC, stryker2k2 commented on bbot/modules/newsletters.py
> +                pass
Roger that - change has been made.

2024-03-07 19:46 UTC, stryker2k2 commented on bbot/modules/dnsdumpster.py
> +            pass
Roger that - change has been made.

2024-03-08 21:20 UTC, TheTechromancer commented
This should good to merge once the last instance is fixed in dnsdumpster.py.

2024-03-13 17:44 UTC, stryker2k2 commented
@TheTechromancer - it is ready for review and merge 😄 I've fixed the last remaining instance in `dnsdumpster`, pulled in `dev`, added in the fix for the new issue that amiremami posted about a few hours ago about the `KeyError: 'body'`

2024-03-13 20:27 UTC, TheTechromancer approved these changes

2024-03-13 20:27 UTC, merged