Add dnscaa module
blacklanternsecurity/bbot pull request #1402
Opened 2024-05-26 22:52 UTC by colin-stubbs

Resolves issue #1400

2024-05-27 05:05 UTC, TheTechromancer requested changes

2024-05-27 05:05 UTC, TheTechromancer commented on bbot/core/helpers/dns.py
> +        elif rdtype == "CAA":
Since this logic is the same as `TXT`, let's merge the two.

2024-05-27 05:05 UTC, TheTechromancer commented on bbot/modules/dnscaa.py
> +    async def filter_event(self, event):
This function can be deleted and the functionality will stay the same

2024-05-27 05:05 UTC, TheTechromancer commented on bbot/modules/dnscaa.py
> +                        s = self.helpers.smart_decode(f"{answer}")
This should probably be `smart_decode(answer.value)`

2024-05-27 05:05 UTC, TheTechromancer commented on bbot/modules/dnscaa.py
> +        except BaseException:
A blanket `except` isn't needed since any module errors are automatically logged, including the traceback.

2024-05-27 05:05 UTC, TheTechromancer commented on bbot/modules/dnscaa.py
> +        self._max_event_handlers = self.config.get("max_event_handlers", 10)
This logic is already handled in the [base class](https://github.com/blacklanternsecurity/bbot/blob/1e2a554d024c1886706f931e9de42c1cc135c4f8/bbot/modules/base.py#L336).

2024-05-27 05:10 UTC, TheTechromancer commented
@colin-stubbs nice work on this. I hadn't heard of CAA records until now so thanks for adding them to BBOT!

How typical is it to see these in the wild? What I'm wondering is whether it's worth trying CAA on everything by default or if we should designate it to the `dnscaa` module.

2024-05-27 07:21 UTC, colin-stubbs commented
> @colin-stubbs nice work on this. I hadn't heard of CAA records until now so thanks for adding them to BBOT!
> 
> How typical is it to see these in the wild? What I'm wondering is whether it's worth doing a CAA lookup on every host by default or if we should leave it to the `dnscaa` module.

To be honest not very typical still.

I've manually poked around a bunch of NASDAQ/ASX traded big name brands, and CAA records of any type are across maybe 5% of them, at most. 

It's more like 1% that actually have an iodef reporting destination advertised at all.

But that's actually why I'm writing this module. I'm using bbot less so from a pen testing perspective, more so from a research perspective, e.g. to determine how widespread adoption is, for what CA's, how common iodef reporting is etc.

CAA records can exist for sub-domains with a different policy to the registered domain, it's not against RFC... hence adding it as a default lookup does make sense. I agree it is perhaps better done by the module though, with some configurable constraint options/filtering so that it's optional to probe subdomains.

I'll go thru the rest of your comments, do some testing, and update the PR.

2024-06-06 00:15 UTC, TheTechromancer commented
@colin-stubbs how are things going?

2024-06-06 07:59 UTC, colin-stubbs commented
> @colin-stubbs how are things going?

Sorted, I've moved all DNS CAA record processing to dnscaa module, tests all pass locally for me.

p.s. by this logic... bbot.core.dns probably shouldn't inspect TXT blindly for DNS_NAME's either.

I've noticed because bbot.core.dns does that, it often leads to spurious results, e.g. as in screenshot below.

Would it not be better to perhaps emit DNS_TXT events, so that other modules that know how to process DNS TXT records more appropriately, can consume them and emit more useful and accurate events?

SPF records are the big one, but Domain Control Validation records also seem to cause some matching issues... though it's also because the dns_name and IPv4 address regex patterning is a bit weak.

NOTE: I do get that by default DNS_UNRESOLVED's get filtered out from results... but it makes sense to me to avoid requesting TXT records multiple times, and instead request once and process as subscribed by modules.

e.g., small sample of some of the garbage,

![Screenshot 2024-06-06 at 5 54 56 PM](https://github.com/blacklanternsecurity/bbot/assets/3059577/017caf0a-d2a8-4a91-90a1-7e632093d602)

2024-06-06 15:04 UTC, TheTechromancer commented
Nice! I'll give this another look.

> Would it not be better to perhaps emit DNS_TXT events
Yes, this is something we definitely want to do. Most likely we will emit a `RAW_DNS_RECORD` or something similar for `MX`, `TXT`, etc.

> Two conceptual modules I've already been working on which could instead consume DNS_TXT events taken from the target level domain and any other inspected DNS_NAME's.
These are both great ideas. 

If you're interested in working on these, please work from the `bbot-2.0` branch, since there have been some changes to DNS that will be difficult to merge in if we make too many changes in the current dev.

2024-06-07 01:47 UTC, TheTechromancer approved these changes

2024-06-07 01:52 UTC, TheTechromancer commented
Made a few small tweaks:

- wrote tests for `in_scope_only` setting 
- updated the tests to use `mock_dns`

And approved. Should be good to merge 👍

2024-06-07 03:06 UTC, liquidsec commented
@colin-stubbs Thanks for the module!

2024-06-07 03:06 UTC, liquidsec approved these changes

2024-06-07 03:30 UTC, merged