Optimized excavate hostname extraction
blacklanternsecurity/bbot pull request #48
Opened 2022-09-14 14:43 UTC by TheTechromancer

Regexes are now only created for parent domains, e.g. so that if 500 subdomains of evilcorp.com are specified as targets, if the base domain is specified as well, only one regex will be created instead of 500.

2022-09-16 21:51 UTC, kerrymilan requested changes
Do we have test coverage for this change?

2022-09-16 21:52 UTC, pmueller-bls reviewed
Not sure I feel comfortable with this until we have tests in place to ensure the correct hostnames are being extracted

2022-09-19 15:41 UTC, pmueller-bls approved these changes

2022-09-19 16:25 UTC, liquidsec approved these changes

2022-09-20 14:17 UTC, TheTechromancer commented
Paul and I manually tested the effectiveness of this change, but we are working on a PR that will enable live-fire testing of modules, including excavate. That will be a big change so it will be pushed from its own branch.

2022-09-21 18:06 UTC, kerrymilan approved these changes

2022-09-21 18:06 UTC, merged