Automate traceback debug logging
blacklanternsecurity/bbot pull request #51
Opened 2022-09-14 15:13 UTC by TheTechromancer

When modules raise a log message using `log.warning()` or similar, the current exception (if there is one) is now logged automatically via `log.debug()`.

2022-09-16 21:58 UTC, kerrymilan approved these changes

2022-09-16 22:03 UTC, pmueller-bls requested changes
Including a traceback should be optional, for example many modules will throw hugewarning when something goes wrong but isn't a crash - example: interactsh cant poll results - that would result in a false-negative condition. In such a case including a traceback would be too verbose.  

Can either make it off by default with the option to turn it on, or on by default with the option of turning it off?

2022-09-17 17:12 UTC, TheTechromancer commented
The traceback will only be displayed in very specific situations. All of these have to be true for it to be displayed:

- a module logs a message with warning level or higher
- there is an active exception when they do this
- you have debugging enabled

2022-09-19 15:12 UTC, pmueller-bls approved these changes

2022-09-19 16:24 UTC, liquidsec approved these changes

2022-09-19 16:36 UTC, merged